name: Temp json
on:
  workflow_dispatch:
    inputs:
      script_name:
        description: 'Name of the Python script to run'
        required: true
        default: 'temp.py'

job:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checking json 
        run: python3 temp.py


