name: testing and deployment

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install httpx

      - name: Run tests
        run: |
          pytest -s tests/
  
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5 

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo -e "[default]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\nregion=${AWS_DEFAULT_REGION}" > ~/.aws/credentials


      - name: Terraform Init
        run: terraform init

      - name: Terraform apply
        if: ${{ github.event.inputs.terraform_action == 'apply'}}
        run: terraform apply -auto-approve
      
      - name: terraform destroy
        if: ${{ github.event.inputs.terraform_action == 'destroy'}}
        run: terraform destroy -auto-approve
